#include <stdint.h>

uint8_t TCCR0A, TCCR0B, TCNT0, OCR0B, OCR0A, DDRA, DDRB, TIMSK0, PORTA, PORTB, TCNT1;
uint8_t TCCR1A, TCCR1B, TIMSK1, DIDR0, ACSR, ADMUX, ADCSRA, ADCSRB, ADCH, ADSC;
uint16_t OCR1A, ICR1;